import os
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

class PDFReporter:
    def __init__(self, target, findings):
        self.target = target
        self.findings = findings
        self.filename = f"Ghost_WebScanner_Report_{target.replace('https://','').replace('http://','')}.pdf"

    def generate(self):
        doc = SimpleDocTemplate(self.filename, pagesize=letter, rightMargin=30, leftMargin=30, topMargin=30, bottomMargin=30)
        story = []
        styles = getSampleStyleSheet()
        
        title_style = ParagraphStyle(
            'TitleStyle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#DC2626'),
            spaceAfter=12
        )
        
        story.append(Paragraph(f"GHOST-WebScanner Security Audit Report", title_style))
        story.append(Paragraph(f"Target: <b>{self.target}</b>", styles['Normal']))
        story.append(Paragraph(f"Generated by Ghost-SY1 Elite Security Engine (2026)", styles['Normal']))
        story.append(Spacer(1, 20))
        
        data = [["CVE ID / Finding", "Product / Endpoint", "Reliability", "Status"]]
        for f in self.findings:
            data.append([f.get('cve', 'Custom Flaw'), f.get('product', f.get('endpoint', 'N/A')), "9.9/10", "VULNERABLE"])
            
        t = Table(data, colWidths=[120, 200, 80, 100])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1E293B')),
            ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0,0), (-1,0), 8),
            ('BACKGROUND', (0,1), (-1,-1), colors.HexColor('#F8FAFC')),
            ('GRID', (0,0), (-1,-1), 1, colors.HexColor('#CBD5E1'))
        ]))
        
        story.append(t)
        doc.build(story)
        return self.filename
